code_review_system:
  logging:
    level: DEBUG
  cache:
    file_cache:
      enabled: true
      timeout: 86400
    mem_cache:
      enabled: true
      timeout: 3600
relation_db:
  db_type: postgresql
  db_host: localhost
  db_port: 5432
  db_name: code_review_db
  db_user: postgres
  db_password: admin
vector_db:
  db_type: chroma
  db_path: /home/zhy/workspace/code-review-system/data/chroma
  db_host: localhost
  db_port: 8000
