# common/settings/celery-config.yaml
broker_url: redis://localhost:6379/0
result_backend: redis://localhost:6379/0
task_serializer: json
accept_content:
  - json
result_serializer: json
timezone: Asia/Shanghai
enable_utc: false
result_expires: 3600
